import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/scss/main.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.mainContent}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Primeiro APP</h1>
      </main>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
        </a>
      </footer>
    </div>
  )
}

export default Home
